idrive:
  container_name: idrive
  image: slayer/idrive
  restart: unless-stopped
  volumes:
    - ./config:/work/IDriveForLinux/idriveIt
    - ./backup:/backup:ro
    # - /mnt/wd0/backups:/backup/wd0-backups:ro

